VENV := justfile_directory() + "/.venv"
PYTHON := justfile_directory() + "/.venv/bin/python"

default:
  @just --list

# Build the package (into `dist/`)
build:
  rm -drf dist
  {{PYTHON}} -m build
  rm -drf build

# Publish `dist/*` to pypi, then delete
publish:
  {{PYTHON}} -m twine upload dist/*
  rm -drf dist

# Increase patch version
patch:
  $BUMP pyproject.toml

# Build and publish
republish: patch build publish

generate-client:
  {{VENV}}/bin/moveread-api-clientgen --package-path client